[package]
name = "kicktick"
version = "0.1.0"
description = "Sub-minute micro prediction markets on Solana (TxODDS oracle settlement)"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "kicktick"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
idl-build = ["anchor-lang/idl-build"]
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = { version = "0.31.1", features = ["init-if-needed"] }
